[project]
name = "lib-tmp-rep"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

[build-system]
requires = ["uv_build>=0.7.21,<0.8"]
build-backend = "uv_build"
